export declare const Add: string
export declare const AddBlock: string
export declare const AddBlockB: string
export declare const AddSqaure: string
export declare const AddSqaureB: string
export declare const AirpodSingle: string
export declare const AirpodSingleB: string
export declare const Airpods: string
export declare const AirpodsAlt: string
export declare const AirpodsAltB: string
export declare const AirpodsB: string
export declare const AirpodsDot: string
export declare const Alarm: string
export declare const AlarmAdd: string
export declare const AlarmAddB: string
export declare const AlarmArrowDown: string
export declare const AlarmArrowDownB: string
export declare const AlarmArrowLeft: string
export declare const AlarmArrowLeftB: string
export declare const AlarmArrowRight: string
export declare const AlarmArrowRightB: string
export declare const AlarmArrowUp: string
export declare const AlarmArrowUpB: string
export declare const AlarmB: string
export declare const AlarmCross: string
export declare const AlarmCrossB: string
export declare const AlarmHeart: string
export declare const AlarmMinus: string
export declare const AlarmMinusB: string
export declare const AlarmStar: string
export declare const AlarmStarB: string
export declare const AlarmTime: string
export declare const AlarmTimeB: string
export declare const AlignBottom: string
export declare const AlignBottomB: string
export declare const AlignCenter: string
export declare const AlignJustify: string
export declare const AlignLeft: string
export declare const AlignRight: string
export declare const AlignTop: string
export declare const AlignTopB: string
export declare const AndroidPhone: string
export declare const AndroidPhoneB: string
export declare const Apps: string
export declare const AppsA: string
export declare const AppsAB: string
export declare const AppsAdd: string
export declare const AppsAddA: string
export declare const AppsAddAB: string
export declare const AppsAddB: string
export declare const AppsB: string
export declare const AppsCross: string
export declare const AppsCrossB: string
export declare const Archive: string
export declare const ArchiveAdd: string
export declare const ArchiveAddB: string
export declare const ArchiveB: string
export declare const ArchiveCross: string
export declare const ArchiveCrossB: string
export declare const ArrowBlockDown: string
export declare const ArrowBlockDownB: string
export declare const ArrowBlockDownleft: string
export declare const ArrowBlockDownleftB: string
export declare const ArrowBlockDownright: string
export declare const ArrowBlockDownrightB: string
export declare const ArrowBlockLeft: string
export declare const ArrowBlockLeftB: string
export declare const ArrowBlockRight: string
export declare const ArrowBlockRightB: string
export declare const ArrowBlockTopleft: string
export declare const ArrowBlockTopleftB: string
export declare const ArrowBlockTopright: string
export declare const ArrowBlockToprightB: string
export declare const ArrowBlockUp: string
export declare const ArrowBlockUpB: string
export declare const ArrowBreakDown: string
export declare const ArrowBreakLeft: string
export declare const ArrowBreakRight: string
export declare const ArrowBreakTop: string
export declare const ArrowCircleDown: string
export declare const ArrowCircleDownB: string
export declare const ArrowCircleDownleft: string
export declare const ArrowCircleDownleftB: string
export declare const ArrowCircleDownright: string
export declare const ArrowCircleDownrightB: string
export declare const ArrowCircleLeft: string
export declare const ArrowCircleLeftB: string
export declare const ArrowCircleRight: string
export declare const ArrowCircleRightB: string
export declare const ArrowCircleTop: string
export declare const ArrowCircleTopB: string
export declare const ArrowCircleTopleft: string
export declare const ArrowCircleTopleftB: string
export declare const ArrowCircleTopright: string
export declare const ArrowCircleToprightB: string
export declare const ArrowCrashDown: string
export declare const ArrowCrashLeft: string
export declare const ArrowCrashRight: string
export declare const ArrowCrashTop: string
export declare const ArrowCurvedDownright: string
export declare const ArrowDoubleheadD: string
export declare const ArrowDoubleheadDA: string
export declare const ArrowDoubleheadH: string
export declare const ArrowDoubleheadV: string
export declare const ArrowDown: string
export declare const ArrowDownleft: string
export declare const ArrowDownright: string
export declare const ArrowDownwards: string
export declare const ArrowDuoDown: string
export declare const ArrowDuoLeft: string
export declare const ArrowDuoRight: string
export declare const ArrowDuoTop: string
export declare const ArrowFullscreen: string
export declare const ArrowLeft: string
export declare const ArrowLoopLeft: string
export declare const ArrowLoopRight: string
export declare const ArrowReverseDownleft: string
export declare const ArrowReverseLongh: string
export declare const ArrowReverseLongv: string
export declare const ArrowReverseShorth: string
export declare const ArrowReverseShortv: string
export declare const ArrowReverseTopleft: string
export declare const ArrowReverseTopright: string
export declare const ArrowRight: string
export declare const ArrowRoundedDownleft: string
export declare const ArrowRoundedDownright: string
export declare const ArrowRoundedTopleft: string
export declare const ArrowRoundedTopright: string
export declare const ArrowSort: string
export declare const ArrowSortB: string
export declare const ArrowSquareDown: string
export declare const ArrowSquareDownB: string
export declare const ArrowSquareDownleft: string
export declare const ArrowSquareDownleftB: string
export declare const ArrowSquareDownright: string
export declare const ArrowSquareDownrightB: string
export declare const ArrowSquareLeft: string
export declare const ArrowSquareLeftB: string
export declare const ArrowSquareRight: string
export declare const ArrowSquareRightB: string
export declare const ArrowSquareTop: string
export declare const ArrowSquareTopB: string
export declare const ArrowSquareTopleft: string
export declare const ArrowSquareTopleftB: string
export declare const ArrowSquareTopright: string
export declare const ArrowSquareToprightB: string
export declare const ArrowTop: string
export declare const ArrowTopleft: string
export declare const ArrowTopright: string
export declare const ArrowTv: string
export declare const ArrowTvDouble: string
export declare const ArrowTvTriple: string
export declare const ArrowUpwards: string
export declare const Atom: string
export declare const Award: string
export declare const AwardB: string
export declare const AwardMinimal: string
export declare const AwardMinimalB: string
export declare const BabyCarriage: string
export declare const BabyCarriageB: string
export declare const Badge: string
export declare const BadgeB: string
export declare const BadgeVarB: string
export declare const Bag: string
export declare const BagAdd: string
export declare const BagAddB: string
export declare const BagAlt: string
export declare const BagAltB: string
export declare const BagB: string
export declare const BagBlock: string
export declare const BagBlockB: string
export declare const BagCheck: string
export declare const BagCheckB: string
export declare const BagCircle: string
export declare const BagCircle1: string
export declare const BagCircleAdd: string
export declare const BagCircleB: string
export declare const BagCircleB1: string
export declare const BagCircleBlock: string
export declare const BagCircleCheck: string
export declare const BagCircleCode: string
export declare const BagCircleCross: string
export declare const BagCode: string
export declare const BagCodeB: string
export declare const BagCross: string
export declare const BagCrossB: string
export declare const Bandaid: string
export declare const BandaidB: string
export declare const BandaidVarB: string
export declare const Bank: string
export declare const BankB: string
export declare const Barchart: string
export declare const BarchartB: string
export declare const BarchartH: string
export declare const BarchartHB: string
export declare const Battery1: string
export declare const Battery1B: string
export declare const Battery2: string
export declare const Battery2B: string
export declare const Battery3: string
export declare const Battery3B: string
export declare const Battery4: string
export declare const Battery4B: string
export declare const Beaker: string
export declare const BeakerB: string
export declare const BeakerHalf: string
export declare const BeakerHalfB: string
export declare const Bed: string
export declare const BedB: string
export declare const Bell: string
export declare const BellB: string
export declare const Board: string
export declare const BoardAdd: string
export declare const BoardB: string
export declare const BoardBlock: string
export declare const BoardChart: string
export declare const BoardChartB: string
export declare const BoardCheck: string
export declare const BoardCode: string
export declare const BoardCodeB: string
export declare const BoardCross: string
export declare const BoardHeart: string
export declare const Bookmark: string
export declare const BookmarkA: string
export declare const BookmarkAB: string
export declare const BookmarkAdd: string
export declare const BookmarkB: string
export declare const BookmarkCross: string
export declare const BookmarkMinus: string
export declare const Bookmarks: string
export declare const BookmarksB: string
export declare const BookmarksBVarB: string
export declare const Bowl: string
export declare const BowlB: string
export declare const Bowling: string
export declare const BowlingB: string
export declare const Box: string
export declare const BoxAdd: string
export declare const BoxAddB: string
export declare const BoxArrowDownleft: string
export declare const BoxArrowDownleftB: string
export declare const BoxArrowTopleft: string
export declare const BoxArrowTopleftB: string
export declare const BoxB: string
export declare const BoxBlock: string
export declare const BoxBlockB: string
export declare const BoxCheck: string
export declare const BoxCheckB: string
export declare const BoxCross: string
export declare const BoxCrossB: string
export declare const BoxCursor: string
export declare const BoxCursorB: string
export declare const BoxDownload: string
export declare const BoxDownloadB: string
export declare const BoxHeart: string
export declare const BoxHeartB: string
export declare const BoxUp: string
export declare const BoxUpB: string
export declare const Braces: string
export declare const Branch: string
export declare const BranchAdd: string
export declare const BranchAddB: string
export declare const BranchB: string
export declare const BranchCheck: string
export declare const BranchCheckB: string
export declare const BranchCross: string
export declare const BranchCrossB: string
export declare const Bread: string
export declare const BreadB: string
export declare const Breadloaf: string
export declare const BringBack: string
export declare const BringFont: string
export declare const BringFontB: string
export declare const Bug: string
export declare const BugB: string
export declare const Bulb: string
export declare const BulbB: string
export declare const Bullseye: string
export declare const BullseyeB: string
export declare const Burger: string
export declare const BurgerB: string
export declare const Button: string
export declare const ButtonB: string
export declare const Cake: string
export declare const Calculator: string
export declare const CalculatorB: string
export declare const Calendar: string
export declare const Calendar7: string
export declare const Calendar7B: string
export declare const CalendarA: string
export declare const CalendarAAdd: string
export declare const CalendarAAddB: string
export declare const CalendarAB: string
export declare const CalendarACheck: string
export declare const CalendarACheckB: string
export declare const CalendarACross: string
export declare const CalendarACrossB: string
export declare const CalendarADot: string
export declare const CalendarADotB: string
export declare const CalendarADots: string
export declare const CalendarADotsB: string
export declare const CalendarAGrid: string
export declare const CalendarAGridB: string
export declare const CalendarAHeart: string
export declare const CalendarAdd: string
export declare const CalendarAddB: string
export declare const CalendarB: string
export declare const CalendarCheck: string
export declare const CalendarCheckB: string
export declare const CalendarCode: string
export declare const CalendarCodeB: string
export declare const CalendarCross: string
export declare const CalendarCrossB: string
export declare const CalendarDash: string
export declare const CalendarDashB: string
export declare const CalendarDot: string
export declare const CalendarDotB: string
export declare const CalendarHeart: string
export declare const CalendarLines: string
export declare const CalendarLinesB: string
export declare const CalendarStar: string
export declare const CalendarStarB: string
export declare const Camera: string
export declare const Camera1: string
export declare const Camera1B: string
export declare const Camera2: string
export declare const Camera2B: string
export declare const CameraB: string
export declare const CameraMinimal: string
export declare const CameraMinimalB: string
export declare const CameraPaper: string
export declare const CameraPaperB: string
export declare const Candy: string
export declare const CandyB: string
export declare const Car: string
export declare const CarB: string
export declare const Card: string
export declare const CardAdd: string
export declare const CardAddB: string
export declare const CardAlt: string
export declare const CardAltB: string
export declare const CardAltVarB: string
export declare const CardB: string
export declare const CardBlock: string
export declare const CardBlockB: string
export declare const CardCheck: string
export declare const CardCheckB: string
export declare const CardCode: string
export declare const CardCodeB: string
export declare const CardCross: string
export declare const CardCrossB: string
export declare const CardDiamond: string
export declare const CardDiamondAlt: string
export declare const CardDiamondAltB: string
export declare const CardDiamondB: string
export declare const CardDownload: string
export declare const CardDownloadB: string
export declare const CardHeart: string
export declare const CardHeartAlt: string
export declare const CardUpload: string
export declare const CardUploadB: string
export declare const CardVarB: string
export declare const CaretDoubleDownleft: string
export declare const CaretDoubleDownleftB: string
export declare const CaretDoubleDownright: string
export declare const CaretDoubleDownrightB: string
export declare const CaretDoubleLeft: string
export declare const CaretDoubleLeftB: string
export declare const CaretDoubleRight: string
export declare const CaretDoubleRight1: string
export declare const CaretDoubleRightB: string
export declare const CaretDoubleRightB1: string
export declare const CaretDoubleTop: string
export declare const CaretDoubleTopB: string
export declare const CaretDoubleTopleft: string
export declare const CaretDoubleTopleftB: string
export declare const CaretDoubleTopright: string
export declare const CaretDoubleToprightB: string
export declare const Cart: string
export declare const CartB: string
export declare const Chalkboard: string
export declare const ChalkboardB: string
export declare const ChartSquare: string
export declare const ChartSquareB: string
export declare const ChartSquareH: string
export declare const ChartSquareHB: string
export declare const CheckCircle: string
export declare const CheckCircleB: string
export declare const CheckSquare: string
export declare const CheckSquareB: string
export declare const Checklist: string
export declare const ChecklistB: string
export declare const ChevronBreakDown: string
export declare const ChevronBreakLeft: string
export declare const ChevronBreakRight: string
export declare const ChevronBreakTop: string
export declare const ChevronCircleDown: string
export declare const ChevronCircleLeft: string
export declare const ChevronCircleRight: string
export declare const ChevronCircleTop: string
export declare const ChevronDoubleDown: string
export declare const ChevronDoubleDownleft: string
export declare const ChevronDoubleDownright: string
export declare const ChevronDoubleLeft: string
export declare const ChevronDoubleRight: string
export declare const ChevronDoubleTop: string
export declare const ChevronDoubleTopleft: string
export declare const ChevronDoubleTopright: string
export declare const ChevronDown: string
export declare const ChevronLeft: string
export declare const ChevronRight: string
export declare const ChevronSquareDown: string
export declare const ChevronSquareDownB: string
export declare const ChevronSquareLeft: string
export declare const ChevronSquareLeftB: string
export declare const ChevronSquareRight: string
export declare const ChevronSquareRightB: string
export declare const ChevronSquareTop: string
export declare const ChevronSquareTopB: string
export declare const ChevronTop: string
export declare const Chip: string
export declare const ChipB: string
export declare const Circle: string
export declare const Circle1: string
export declare const Circle10: string
export declare const Circle10B: string
export declare const Circle11: string
export declare const Circle11B: string
export declare const Circle12: string
export declare const Circle12B: string
export declare const Circle12VarB: string
export declare const Circle13: string
export declare const Circle13B: string
export declare const Circle13VarB: string
export declare const Circle14: string
export declare const Circle14AltVarB: string
export declare const Circle14B: string
export declare const Circle14VarB: string
export declare const Circle15: string
export declare const Circle15B: string
export declare const Circle15VarB: string
export declare const Circle1B: string
export declare const Circle1VarB: string
export declare const Circle2: string
export declare const Circle2B: string
export declare const Circle2VarB: string
export declare const Circle3: string
export declare const Circle3B: string
export declare const Circle3VarB: string
export declare const Circle4: string
export declare const Circle4B: string
export declare const Circle4VarB: string
export declare const Circle5: string
export declare const Circle5B: string
export declare const Circle6: string
export declare const Circle6B: string
export declare const Circle7: string
export declare const Circle7B: string
export declare const Circle8: string
export declare const Circle8B: string
export declare const Circle9: string
export declare const Circle9B: string
export declare const CircleB: string
export declare const CircleHeart: string
export declare const CircleTimes: string
export declare const ClockCircle: string
export declare const ClockCircleB: string
export declare const ClockSqaure: string
export declare const ClockSqaureB: string
export declare const Cloud: string
export declare const CloudB: string
export declare const CloudCircle: string
export declare const CloudCircleB: string
export declare const CloudSun: string
export declare const CloudSunB: string
export declare const CloudSunVarB: string
export declare const Coathanger: string
export declare const CoathangerB: string
export declare const CodeBox: string
export declare const CodeBoxAlt: string
export declare const CodeBoxAltB: string
export declare const CodeBoxB: string
export declare const CodeCircle: string
export declare const CodeCircleB: string
export declare const CodeCircleVertical: string
export declare const CodeCircleVerticalB: string
export declare const CodeHex: string
export declare const CodeHexB: string
export declare const CodeHexVertical: string
export declare const CodeHexVerticalB: string
export declare const CodeRectanlge: string
export declare const CodeRectanlgeB: string
export declare const CodeSquare: string
export declare const CodeSquareB: string
export declare const CodeSquareVertical: string
export declare const CodeSquareVerticalB: string
export declare const Coin: string
export declare const CoinB: string
export declare const Coins: string
export declare const CoinsB: string
export declare const CommentHeart: string
export declare const CompassCircle: string
export declare const CompassCircleB: string
export declare const CompassSquare: string
export declare const CompassSquareB: string
export declare const Copy: string
export declare const CopyA: string
export declare const CopyAB: string
export declare const CopyAVarB: string
export declare const CopyB: string
export declare const CopyOverlap: string
export declare const CopyOverlapB: string
export declare const CopySquare: string
export declare const CopySquareB: string
export declare const CopySquareB1: string
export declare const CricketBall: string
export declare const CricketBallB: string
export declare const Cross: string
export declare const CrossBlock: string
export declare const CrossBlockB: string
export declare const CrossSquare: string
export declare const CrossSquareB: string
export declare const Crown: string
export declare const CrownAlt: string
export declare const CrownAltB: string
export declare const CrownB: string
export declare const CubeOverlap: string
export declare const Cup: string
export declare const CupAlt: string
export declare const CupAltB: string
export declare const CupB: string
export declare const CupSmooth: string
export declare const CupSmoothAlt: string
export declare const CupSmoothAltB: string
export declare const CupSmoothB: string
export declare const Currency: string
export declare const CurrencyAlt: string
export declare const CurrencyAltB: string
export declare const CurrencyAltVarB: string
export declare const CurrencyVarB: string
export declare const Cursor: string
export declare const CursorB: string
export declare const CursorCircle: string
export declare const CursorCircle1: string
export declare const CursorCircleB: string
export declare const CursorCircleB1: string
export declare const CursorCircleDashed: string
export declare const CursorCircleDashedB: string
export declare const CursorSqaureAlt: string
export declare const CursorSqaureAltB: string
export declare const CursorSqaureAltDashed: string
export declare const CursorSqaureAltDashedB: string
export declare const CursorSquare: string
export declare const CursorSquareB: string
export declare const CursorSquareDashed: string
export declare const CursorSquareDashedB: string
export declare const CurvedRectangle: string
export declare const CurvedRectangleA: string
export declare const CurvedRectangleAB: string
export declare const CurvedRectangleB: string
export declare const CurvedSquare: string
export declare const CurvedSquareB: string
export declare const Cylinder: string
export declare const CylinderA: string
export declare const CylinderAB: string
export declare const CylinderB: string
export declare const Dashboard: string
export declare const DashboardGrid: string
export declare const DashboardGridB: string
export declare const DashboardSemi: string
export declare const DashboardSemiB: string
export declare const DashboardSquare: string
export declare const DashboardSquareB: string
export declare const DashedCircle: string
export declare const DashedSquare: string
export declare const DashedSquareA: string
export declare const Database: string
export declare const DatabaseB: string
export declare const Delete: string
export declare const DeleteA: string
export declare const DeleteAB: string
export declare const DeleteB: string
export declare const DesignAlignCenter: string
export declare const DesignAlignCenterB: string
export declare const DesignAlignLeft: string
export declare const DesignAlignLeftB: string
export declare const DesignAlignRight: string
export declare const DesignAlignRightB: string
export declare const Diamond: string
export declare const DiamondAdd: string
export declare const DiamondAlt: string
export declare const DiamondB: string
export declare const DiamondBlock: string
export declare const DiamondCheck: string
export declare const DiamondCode: string
export declare const DiamondCross: string
export declare const DiamondHear: string
export declare const DiamondRing: string
export declare const DiamondRingB: string
export declare const Dice: string
export declare const Dice1: string
export declare const Dice2: string
export declare const Dice2B: string
export declare const Dice3: string
export declare const Dice3B: string
export declare const Dice4: string
export declare const Dice4B: string
export declare const Dice5: string
export declare const Dice5B: string
export declare const Dice6: string
export declare const Dice6B: string
export declare const DiceAdd: string
export declare const DiceBlock: string
export declare const DiceCross: string
export declare const DiceHeart: string
export declare const Dices: string
export declare const DicesB: string
export declare const DicesVarB: string
export declare const Discount: string
export declare const DiscountB: string
export declare const Dislike: string
export declare const DislikeB: string
export declare const DislikeVarB: string
export declare const DivideBlock: string
export declare const DivideBlockB: string
export declare const Door: string
export declare const DoorB: string
export declare const DotdotType: string
export declare const Download: string
export declare const Drawer: string
export declare const DrawerB: string
export declare const Dumbell: string
export declare const DumbellAlt: string
export declare const DumbellAltB: string
export declare const DumbellB: string
export declare const Earth: string
export declare const EarthB: string
export declare const EarthVarB: string
export declare const Edit: string
export declare const EditB: string
export declare const EditSquare: string
export declare const EditSquareB: string
export declare const Egg: string
export declare const EggB: string
export declare const EllipsisDoubleH: string
export declare const EllipsisDoubleHB: string
export declare const EllipsisDoubleV: string
export declare const EllipsisDoubleVB: string
export declare const EllipsisH: string
export declare const EllipsisHB: string
export declare const EllipsisHCircle: string
export declare const EllipsisHCircleB: string
export declare const EllipsisHPill: string
export declare const EllipsisHPillB: string
export declare const EllipsisHSquare: string
export declare const EllipsisHSquareB: string
export declare const EllipsisV: string
export declare const EllipsisVB: string
export declare const EllipsisVCircle: string
export declare const EllipsisVCircle1: string
export declare const EllipsisVCircleB: string
export declare const EllipsisVPill: string
export declare const EllipsisVPillB: string
export declare const EllipsisVSquareB: string
export declare const Emrald: string
export declare const EmraldB: string
export declare const EqualSquare: string
export declare const EqualSquareB: string
export declare const ErrorCircle: string
export declare const ErrorCircleB: string
export declare const ErrorHexagon: string
export declare const ErrorHexagonB: string
export declare const ErrorSquare: string
export declare const ErrorSquareB: string
export declare const Explosive: string
export declare const ExplosiveB: string
export declare const Eyeliner: string
export declare const EyelinerB: string
export declare const Female: string
export declare const FemaleB: string
export declare const File: string
export declare const FileAdd: string
export declare const FileAddB: string
export declare const FileB: string
export declare const FileBlock: string
export declare const FileBlockB: string
export declare const FileCheck: string
export declare const FileCheckB: string
export declare const FileCode: string
export declare const FileCodeB: string
export declare const FileCross: string
export declare const FileCrossB: string
export declare const FileDownload: string
export declare const FileDownloadB: string
export declare const FileHeart: string
export declare const FileInFolder: string
export declare const FileInFolderB: string
export declare const FileInFolderVarB: string
export declare const FileUpload: string
export declare const FileUploadB: string
export declare const FileVarB: string
export declare const Flag: string
export declare const FlagAlt: string
export declare const FlagAltB: string
export declare const FlagAltVarB: string
export declare const FlagB: string
export declare const FlagTriangle: string
export declare const FlagTriangleB: string
export declare const Flask: string
export declare const FlaskB: string
export declare const FlexStand: string
export declare const FlexStandB: string
export declare const FlexStandFilled: string
export declare const FlexStandFilledB: string
export declare const Folder: string
export declare const FolderAdd: string
export declare const FolderAddB: string
export declare const FolderB: string
export declare const FolderBlock: string
export declare const FolderBlockB: string
export declare const FolderCheck: string
export declare const FolderCheckB: string
export declare const FolderCross: string
export declare const FolderCrossB: string
export declare const FolderHeart: string
export declare const FolderHeartB: string
export declare const FoldersShelf: string
export declare const FoldersShelfB: string
export declare const Football: string
export declare const FootballA: string
export declare const FootballAB: string
export declare const FootballB: string
export declare const Fork: string
export declare const ForkB: string
export declare const ForkDiag: string
export declare const ForkDiagB: string
export declare const Frame1039: string
export declare const Frame964: string
export declare const Fruits: string
export declare const Gameboy: string
export declare const GameboyB: string
export declare const Git: string
export declare const GitAlt: string
export declare const GitAltB: string
export declare const GitArrowUp: string
export declare const GitArrowUpB: string
export declare const GitB: string
export declare const Glass: string
export declare const GlassHalf: string
export declare const GlassHalfB: string
export declare const GlassStraw: string
export declare const GlassStrawB: string
export declare const Graphdown: string
export declare const GraphdownB: string
export declare const Graphup: string
export declare const GraphupB: string
export declare const Guitar: string
export declare const HandheldConsole: string
export declare const HandheldConsoleB: string
export declare const Hashtag: string
export declare const HashtagCircle: string
export declare const HashtagCircleB: string
export declare const HashtagSquare: string
export declare const HashtagSquareB: string
export declare const Hat: string
export declare const HatB: string
export declare const Headphone: string
export declare const HeadphoneAdd: string
export declare const HeadphoneAddB: string
export declare const HeadphoneB: string
export declare const HeadphoneCross: string
export declare const HeadphoneCrossB: string
export declare const HeadphoneFancy: string
export declare const HeadphoneFancyB: string
export declare const Heart: string
export declare const HeartB: string
export declare const HeartHalf: string
export declare const HeartRate: string
export declare const Heartrate: string
export declare const Hearts: string
export declare const HeartsAlt: string
export declare const HeartsB: string
export declare const Heptagon: string
export declare const HeptagonB: string
export declare const HexAdd: string
export declare const HexAddB: string
export declare const HexCross: string
export declare const HexCross1: string
export declare const HexCrossB: string
export declare const HexCrossB1: string
export declare const Hockey: string
export declare const HockeyB: string
export declare const HomeCh: string
export declare const HomeChB: string
export declare const HomeCircle: string
export declare const HomeCircle1: string
export declare const HomeCircleB: string
export declare const HomeCircleB1: string
export declare const HomeCircleCh: string
export declare const HomeCircleChB: string
export declare const HomeEmpty: string
export declare const HomeEmptyB: string
export declare const HomeGarage: string
export declare const HomeGarageB: string
export declare const HomeGarageCircle: string
export declare const HomeGarageCircleChA: string
export declare const HomeGarageCircleChAB: string
export declare const HomeGarageCircleVarB: string
export declare const HomeGarageLine: string
export declare const HomeGarageLineB: string
export declare const HomeLargedoor: string
export declare const HomeLargedoorB: string
export declare const HomeLargedoorCircle: string
export declare const HomeLargedoorCircleB: string
export declare const HomeLargedoorCircleCh: string
export declare const HomeLargedoorCircleChB: string
export declare const HomeMinimal: string
export declare const HomeMinimalB: string
export declare const Icecream: string
export declare const IcecreamB: string
export declare const IcecreamVarB: string
export declare const IdCircle: string
export declare const IdCircleB: string
export declare const IdCircleVarB: string
export declare const IdSquare: string
export declare const IdSquareB: string
export declare const IdSquareVarB: string
export declare const Image: string
export declare const ImageAdd: string
export declare const ImageAddB: string
export declare const ImageAlt: string
export declare const ImageAltB: string
export declare const ImageB: string
export declare const ImageBlock: string
export declare const ImageBlockB: string
export declare const ImageCheck: string
export declare const ImageCheckB: string
export declare const ImageCircleAlt: string
export declare const ImageCircleAltB: string
export declare const ImageCross: string
export declare const ImageCrossB: string
export declare const ImageMinimal: string
export declare const ImageMinimalB: string
export declare const ImageMinimalCircle: string
export declare const ImageMinimalCircleB: string
export declare const ImageMountains: string
export declare const ImageMountainsB: string
export declare const ImageMountainsCircle: string
export declare const ImageMountainsCircleB: string
export declare const ImageVarB: string
export declare const Images: string
export declare const ImagesB: string
export declare const ImagesVarB: string
export declare const ImaheCircle: string
export declare const Inbox: string
export declare const InboxB: string
export declare const InboxCircle: string
export declare const InboxCircleB: string
export declare const InboxEmpty: string
export declare const InboxEmptyB: string
export declare const InboxVarB: string
export declare const Incognito: string
export declare const IncognitoB: string
export declare const InfoCircle: string
export declare const InfoCircleB: string
export declare const InfoOctagon: string
export declare const InfoOctagonB: string
export declare const InfoSquare: string
export declare const InfoSquareB: string
export declare const Intersection: string
export declare const Iphone: string
export declare const Italics: string
export declare const Joystick: string
export declare const JoystickAlt: string
export declare const JoystickAltB: string
export declare const JoystickB: string
export declare const JoystickCute: string
export declare const JoystickCuteB: string
export declare const Key: string
export declare const KeyB: string
export declare const KeyStraight: string
export declare const KeyStraightB: string
export declare const Keypad: string
export declare const KeypadB: string
export declare const Knife: string
export declare const KnifeB: string
export declare const Knight: string
export declare const KnightB: string
export declare const Laptop: string
export declare const LaptopAdd: string
export declare const LaptopAddB: string
export declare const LaptopB: string
export declare const LaptopBlock: string
export declare const LaptopBlockB: string
export declare const LaptopCheck: string
export declare const LaptopCheckB: string
export declare const LaptopCode: string
export declare const LaptopCodeB: string
export declare const LaptopCross: string
export declare const LaptopCrossB: string
export declare const LaptopSlanted: string
export declare const LaptopSlantedB: string
export declare const Like: string
export declare const Like1: string
export declare const LikeB: string
export declare const LikeVarB: string
export declare const LineUp: string
export declare const LineUpB: string
export declare const Link: string
export declare const Lipstick: string
export declare const LipstickB: string
export declare const Lock: string
export declare const LockAlt: string
export declare const LockAltB: string
export declare const LockB: string
export declare const LockKeyhole: string
export declare const LockKeyholeB: string
export declare const LockOpen: string
export declare const LockOpenB: string
export declare const LockPartialopen: string
export declare const LockPartialopenB: string
export declare const LogIn: string
export declare const LogOut: string
export declare const Magicwand: string
export declare const MagicwandB: string
export declare const Mail: string
export declare const MailAdd: string
export declare const MailAlt: string
export declare const MailB: string
export declare const MailBranch: string
export declare const MailBranchAlt: string
export declare const MailBranchAltB: string
export declare const MailBranchB: string
export declare const MailCheck: string
export declare const MailCode: string
export declare const MailCross: string
export declare const MailDownright: string
export declare const MailOutline: string
export declare const MailTopleft: string
export declare const Male: string
export declare const MaleB: string
export declare const Mantra: string
export declare const MantraB: string
export declare const Map: string
export declare const MapAlt: string
export declare const MapB: string
export declare const MapPin: string
export declare const MapPinB: string
export declare const Message: string
export declare const MessageAdd: string
export declare const MessageAlt: string
export declare const MessageAltB: string
export declare const MessageB: string
export declare const MessageCircle: string
export declare const MessageCircleAdd: string
export declare const MessageCircleAddB: string
export declare const MessageCircleB: string
export declare const MessageCircleCross: string
export declare const MessageCircleCrossB: string
export declare const MessageCode: string
export declare const MessageCross: string
export declare const MessageHeart: string
export declare const MessageMinimal: string
export declare const MessageMinimalAdd: string
export declare const MessageMinimalB: string
export declare const MessageMinimalCheck: string
export declare const MessageMinimalCross: string
export declare const MessageMinimalHeart: string
export declare const MessageSearch: string
export declare const MessageSearchB: string
export declare const MessageUser: string
export declare const MessageUserB: string
export declare const Meter: string
export declare const MeterB: string
export declare const Mic: string
export declare const MicAlt: string
export declare const MicB: string
export declare const MicCircle: string
export declare const MicCircleB: string
export declare const MicCircleDashed: string
export declare const MicCircleDashedB: string
export declare const MicEmpty: string
export declare const MicEmptyB: string
export declare const MicSquare: string
export declare const MicSquareAlt: string
export declare const MicSquareAltB: string
export declare const MicSquareB: string
export declare const Microphone: string
export declare const MicrophoneB: string
export declare const MinusBlock: string
export declare const MinusBlockB: string
export declare const MinusSquare: string
export declare const MinusSquareB: string
export declare const Money: string
export declare const MoneyAdd: string
export declare const MoneyAddB: string
export declare const MoneyB: string
export declare const MoneyBlock: string
export declare const MoneyBlockB: string
export declare const MoneyCheck: string
export declare const MoneyCheckB: string
export declare const MoneyCode: string
export declare const MoneyCodeB: string
export declare const MoneyCross: string
export declare const MoneyCrossB: string
export declare const MoneyDiag: string
export declare const MoneyDiagB: string
export declare const MoneyDiagVarB: string
export declare const MoneyHeart: string
export declare const MoneyHeartB: string
export declare const MoneyStack: string
export declare const MoneyStackB: string
export declare const MoneyStackVarB: string
export declare const MoneyVarB: string
export declare const Monitor: string
export declare const MonitorAlt: string
export declare const MonitorAltB: string
export declare const MonitorB: string
export declare const MonitorBack: string
export declare const MonitorBackB: string
export declare const MonitorBackVarB: string
export declare const MonitorDownload: string
export declare const MonitorMac: string
export declare const MonitorMacAlt: string
export declare const MonitorMacAltB: string
export declare const MonitorMacAltVarB: string
export declare const MonitorMacB: string
export declare const MonitorMacVarB: string
export declare const MonitorReception: string
export declare const MonitorReceptionB: string
export declare const MonitorTriangle: string
export declare const MonitorTriangleB: string
export declare const MonitorUpload: string
export declare const Moon: string
export declare const Mountains: string
export declare const MountainsB: string
export declare const Mouse: string
export declare const MouseAlt: string
export declare const MouseAltB: string
export declare const MouseApple: string
export declare const MouseB: string
export declare const Movie: string
export declare const MovieAdd: string
export declare const MovieAddB: string
export declare const MovieB: string
export declare const MovieBlock: string
export declare const MovieCheck: string
export declare const MovieCheckB: string
export declare const MovieCross: string
export declare const MovieCrossB: string
export declare const MovieHeart: string
export declare const MoviePause: string
export declare const MoviePauseB: string
export declare const Nav: string
export declare const NavAlt: string
export declare const NavAltB: string
export declare const NavAltVarB: string
export declare const NavB: string
export declare const NavDiag: string
export declare const NavDiagB: string
export declare const NineKey: string
export declare const NineKeyB: string
export declare const NoEntry: string
export declare const NoEntryB: string
export declare const NoEntryVarB: string
export declare const NoteLocate: string
export declare const NoteLocateB: string
export declare const NotePinned: string
export declare const NotePinnedB: string
export declare const NotePinnedFilled: string
export declare const NotePinnedFilledB: string
export declare const NoteSearch: string
export declare const NoteSearchB: string
export declare const Notebook: string
export declare const NotebookOpen: string
export declare const NotebookOpenB: string
export declare const Notes: string
export declare const NotesB: string
export declare const NotesPaper: string
export declare const NotesPaperB: string
export declare const NotesVarB: string
export declare const Notification: string
export declare const NotificationAlert: string
export declare const NotificationAlertA: string
export declare const NotificationAlertAB: string
export declare const NotificationAlertB: string
export declare const NotificationB: string
export declare const NotificationMinimal: string
export declare const NotificationMinimalAlert: string
export declare const NotificationMinimalAlertA: string
export declare const NotificationMinimalAlertAB: string
export declare const NotificationMinimalAlertB: string
export declare const NotificationMinimalB: string
export declare const Octagon: string
export declare const OctagonB: string
export declare const Omlette: string
export declare const OmletteB: string
export declare const Paintbrush: string
export declare const PaintbrushAlt: string
export declare const PaintbrushAltB: string
export declare const PaintbrushB: string
export declare const PaintbrushVarB: string
export declare const Palette: string
export declare const PaletteB: string
export declare const PaletteVarB: string
export declare const ParaAdd: string
export declare const ParaBlock: string
export declare const ParaCheck: string
export declare const ParaCircle: string
export declare const ParaCircleB: string
export declare const ParaCross: string
export declare const ParaHeart: string
export declare const ParaPlay: string
export declare const ParaPlayB: string
export declare const ParaSearch: string
export declare const ParaSearchB: string
export declare const ParabolaDown: string
export declare const ParabolaUp: string
export declare const ParallelogramTool: string
export declare const ParallelogramToolAlt: string
export declare const ParallelogramToolAltB: string
export declare const ParallelogramToolB: string
export declare const PercentBlock: string
export declare const PercentBlockB: string
export declare const Phone: string
export declare const PhoneAdd: string
export declare const PhoneAddB: string
export declare const PhoneB: string
export declare const PhoneBlock: string
export declare const PhoneBlockB: string
export declare const PhoneCheck: string
export declare const PhoneCheckB: string
export declare const PhoneClassic: string
export declare const PhoneClassicB: string
export declare const PhoneClassicVarB: string
export declare const PhoneCross: string
export declare const PhoneCrossB: string
export declare const PhoneHeart: string
export declare const PhoneHeartB: string
export declare const PhoneIncoming: string
export declare const PhoneIncomingB: string
export declare const PhoneMissed: string
export declare const PhoneMissedB: string
export declare const PhoneOutgoing: string
export declare const PhoneOutgoingB: string
export declare const PhonePlay: string
export declare const PhonePlayB: string
export declare const Piano: string
export declare const PianoB: string
export declare const Pie: string
export declare const PieAlt: string
export declare const PieB: string
export declare const PieDivided: string
export declare const PieDividedB: string
export declare const PieHalf: string
export declare const PieHalfB: string
export declare const PieHalfVarB: string
export declare const PieVarB: string
export declare const Pin: string
export declare const PinAdd: string
export declare const PinAddB: string
export declare const PinB: string
export declare const PinCircle: string
export declare const PinCircleB: string
export declare const PinCross: string
export declare const PinCrossB: string
export declare const Pizzatime: string
export declare const PizzatimeB: string
export declare const Plant: string
export declare const PlantB: string
export declare const PlantVarB: string
export declare const Play: string
export declare const PlayCircle: string
export declare const PlayCircleB: string
export declare const PlayCircleDashed: string
export declare const PlayCircleDashedB: string
export declare const PlayEqual: string
export declare const PlayEqualB: string
export declare const PlayHex: string
export declare const PlayHexB: string
export declare const PlayHexVarB: string
export declare const PlayPause: string
export declare const PlayPauseB: string
export declare const PlaySqaure: string
export declare const PlaySqaureB: string
export declare const PlaySquareDashed: string
export declare const PlaySquareDashedB: string
export declare const Popsicle: string
export declare const PopsicleB: string
export declare const PowerButton: string
export declare const Presentation: string
export declare const PresentationAlt: string
export declare const PresentationAltB: string
export declare const PresentationAltVarB: string
export declare const PresentationB: string
export declare const PresentationChart: string
export declare const PresentationChartB: string
export declare const Printer: string
export declare const PrinterB: string
export declare const PrinterVarB: string
export declare const Projector: string
export declare const ProjectorB: string
export declare const Pumpkin: string
export declare const PumpkinB: string
export declare const PumpkinVarB: string
export declare const Puzzle: string
export declare const PuzzleB: string
export declare const Radio: string
export declare const Radio1: string
export declare const RadioB: string
export declare const RadioButton: string
export declare const RadioButtonB: string
export declare const Rain: string
export declare const RainB: string
export declare const ReactangleHalf: string
export declare const ReactangleHalfB: string
export declare const Reel: string
export declare const ReelAdd: string
export declare const ReelBlock: string
export declare const ReelCheck: string
export declare const ReelCode: string
export declare const ReelCross: string
export declare const Responsive: string
export declare const ResponsiveB: string
export declare const ResponsiveVarB: string
export declare const Rhombus: string
export declare const RhombusB: string
export declare const Rugby: string
export declare const RugbyHelmet: string
export declare const RugbyHelmetB: string
export declare const Ruler: string
export declare const RulerDiag: string
export declare const Sanitizer: string
export declare const SanitizerB: string
export declare const SanitizerMinimal: string
export declare const SanitizerMinimalB: string
export declare const Save: string
export declare const SaveB: string
export declare const SaveVarB: string
export declare const Scan: string
export declare const ScanAdd: string
export declare const ScanBlock: string
export declare const ScanCamera: string
export declare const ScanCameraB: string
export declare const ScanCheck: string
export declare const ScanCode: string
export declare const ScanCross: string
export declare const ScanKey: string
export declare const ScanKeyB: string
export declare const ScanLock: string
export declare const ScanLockB: string
export declare const ScanSearch: string
export declare const ScanSearchB: string
export declare const Scooter: string
export declare const ScooterB: string
export declare const ScooterVarB: string
export declare const ScrollH: string
export declare const ScrollHB: string
export declare const ScrollV: string
export declare const ScrollVB: string
export declare const Search: string
export declare const SearchAdd: string
export declare const SearchAddB: string
export declare const SearchB: string
export declare const SearchCircle: string
export declare const SearchCross: string
export declare const SearchCrossB: string
export declare const SearchHeart: string
export declare const SearchMinus: string
export declare const SearchMinusB: string
export declare const SearchSquare: string
export declare const SearchSquareB: string
export declare const SendMessage: string
export declare const Server: string
export declare const ServerB: string
export declare const ServerDivided: string
export declare const ServerDividedB: string
export declare const SettingsCog: string
export declare const SettingsCogB: string
export declare const SettingsHorizontal: string
export declare const SettingsHorizontalB: string
export declare const SettingsVertical: string
export declare const SettingsVerticalB: string
export declare const SevenKey: string
export declare const SevenKeyB: string
export declare const Shield: string
export declare const ShieldAdd: string
export declare const ShieldAddB: string
export declare const ShieldB: string
export declare const ShieldBlock: string
export declare const ShieldBlockB: string
export declare const ShieldCheck: string
export declare const ShieldCheckB: string
export declare const ShieldCode: string
export declare const ShieldCodeB: string
export declare const ShieldCross: string
export declare const ShieldCrossB: string
export declare const ShieldHeart: string
export declare const ShieldImage: string
export declare const ShieldImageB: string
export declare const ShieldScroll: string
export declare const ShieldScrollB: string
export declare const Signal: string
export declare const Simcard: string
export declare const SimcardB: string
export declare const SmartwatcCircle: string
export declare const SmartwatcCircleB: string
export declare const SmartwatcCircleTime: string
export declare const SmartwatcCircleTimeB: string
export declare const SmartwatcSquare: string
export declare const SmartwatcSquareB: string
export declare const SmartwatcSquareTime: string
export declare const SmartwatcSquareTimeB: string
export declare const Snow: string
export declare const SnowB: string
export declare const Sound: string
export declare const SoundB: string
export declare const Speaker: string
export declare const SpeakerB: string
export declare const Spoon: string
export declare const SpoonB: string
export declare const SpoonDiag: string
export declare const SpoonDiagB: string
export declare const Square: string
export declare const Square1: string
export declare const Square10: string
export declare const Square10B: string
export declare const Square11: string
export declare const Square11B: string
export declare const Square12: string
export declare const Square12B: string
export declare const Square12VarB: string
export declare const Square13: string
export declare const Square13B: string
export declare const Square13VarB: string
export declare const Square14: string
export declare const Square14B: string
export declare const Square14VarB: string
export declare const Square15: string
export declare const Square15B: string
export declare const Square1B: string
export declare const Square1VarB: string
export declare const Square2: string
export declare const Square2B: string
export declare const Square2VarB: string
export declare const Square3: string
export declare const Square3B: string
export declare const Square3VarB: string
export declare const Square4: string
export declare const Square4B: string
export declare const Square4VarB: string
export declare const Square5: string
export declare const Square5B: string
export declare const Square6: string
export declare const Square6B: string
export declare const Square7: string
export declare const Square7B: string
export declare const Square8: string
export declare const Square8B: string
export declare const Square9: string
export declare const Square9B: string
export declare const SquareB: string
export declare const SquareCircle: string
export declare const SquareCircleB: string
export declare const SquareDiagCircle: string
export declare const SquareDiagCircleB: string
export declare const SquareDiagHalf: string
export declare const SquareDiagHalfB: string
export declare const SquareDiagHalfVarB: string
export declare const SquareHeart: string
export declare const SquareTool: string
export declare const SquareToolB: string
export declare const Stack: string
export declare const StackAlt: string
export declare const StackAltB: string
export declare const StackB: string
export declare const Star: string
export declare const StarB: string
export declare const StarHalfB: string
export declare const StarWand: string
export declare const StarWandB: string
export declare const Stethoscope: string
export declare const StethoscopeB: string
export declare const Stickynote: string
export declare const StickynoteB: string
export declare const StickynoteVarB: string
export declare const Suitcase: string
export declare const SuitcaseB: string
export declare const SuitcaseMinimal: string
export declare const SuitcaseMinimalB: string
export declare const SuitcaseVarB: string
export declare const SunCloud: string
export declare const SunCloudB: string
export declare const SunCloudVarB: string
export declare const Switch: string
export declare const SwitchActive: string
export declare const SwitchAdd: string
export declare const SwitchAddB: string
export declare const SwitchCross: string
export declare const SwitchCrossB: string
export declare const Sword: string
export declare const SwordB: string
export declare const Target: string
export declare const Tennis: string
export declare const TennisB: string
export declare const TennisVarB: string
export declare const Terminal: string
export declare const TerminalB: string
export declare const Tetris1: string
export declare const Tetris1B: string
export declare const Tetris2: string
export declare const Tetris2B: string
export declare const Tetris3: string
export declare const Tetris3B: string
export declare const Tetris4: string
export declare const Tetris4B: string
export declare const Tetris5: string
export declare const Tetris5B: string
export declare const Tetris6: string
export declare const Tetris6B: string
export declare const Tetris7: string
export declare const Tetris7B: string
export declare const Tetris8: string
export declare const Tetris8B: string
export declare const Tetris9: string
export declare const Tetris9B: string
export declare const Tie: string
export declare const TieAlt: string
export declare const TieB: string
export declare const TiePattern: string
export declare const TiePatternB: string
export declare const Tree: string
export declare const Triangle: string
export declare const TriangleAlt: string
export declare const TriangleB: string
export declare const TriangleReverse: string
export declare const TriangleReverseB: string
export declare const Tv: string
export declare const TvAlt: string
export declare const TvAltB: string
export declare const TvAltVarB: string
export declare const TvB: string
export declare const TypeDotdot: string
export declare const Underline: string
export declare const Underpants: string
export declare const UnderpantsB: string
export declare const UnderpantsButton: string
export declare const UnderpantsButtonB: string
export declare const UnderpantsVarB: string
export declare const Union: string
export declare const Union3: string
export declare const UnionB: string
export declare const UnionVarB: string
export declare const Upload: string
export declare const UsbDrive: string
export declare const UsbDriveB: string
export declare const UsbDriveVarB: string
export declare const User: string
export declare const UserAdd: string
export declare const UserAddB: string
export declare const UserB: string
export declare const UserBlock: string
export declare const UserBlockB: string
export declare const UserCheck: string
export declare const UserCircle: string
export declare const UserCircleAdd: string
export declare const UserCircleAddB: string
export declare const UserCircleB: string
export declare const UserCircleBlock: string
export declare const UserCircleBlockB: string
export declare const UserCircleCheck: string
export declare const UserCircleCheckB: string
export declare const UserCircleCode: string
export declare const UserCircleCodeB: string
export declare const UserCircleCross: string
export declare const UserCircleCrossB: string
export declare const UserCircleHeart: string
export declare const UserCircleHeartB: string
export declare const UserCross: string
export declare const UserCrossB: string
export declare const UserDownload: string
export declare const UserDownloadB: string
export declare const UserHeart: string
export declare const UserHeartB: string
export declare const UserSqaureBlock: string
export declare const UserSqaureBlockB: string
export declare const UserSqaureCheck: string
export declare const UserSqaureCheckB: string
export declare const UserSqaureCode: string
export declare const UserSqaureCodeB: string
export declare const UserSquare: string
export declare const UserSquareAdd: string
export declare const UserSquareAddB: string
export declare const UserSquareB: string
export declare const UserSquareHeart: string
export declare const UserSquareHeartB: string
export declare const UserUpload: string
export declare const UserUploadB: string
export declare const Users: string
export declare const UsersB: string
export declare const Verify: string
export declare const VerifyA: string
export declare const VerifyAB: string
export declare const VerifyB: string
export declare const Wallet: string
export declare const WalletB: string
export declare const Warning: string
export declare const WarningB: string
export declare const Webcam: string
export declare const WebcamB: string
export declare const Weighingmachine: string
export declare const WeighingmachineB: string
export declare const Wine: string
export declare const WineB: string
export declare const WineHalf: string
export declare const WineHalfB: string
export declare const YogaMat: string
export declare const YogaMatB: string
